### ISSUE TITLE
Clip to State Boundary

### ISSUE THREAD

**Issue by jpechmann** [agrc/starch#60]
As part of update script, clip broadband data to state boundary. Use SGID10.BOUNDARIES.Utah.

**Comment by stdavis** [comment]
@jpechmann: I checked the data in UBBMAP and it appears that it's already clipped to the state boundary. Is this issue still valid?

**Comment by jpechmann** [comment]
@stdavis I'm going to say no... I can't remember the details on this one.

**Comment by stdavis** [comment]
OK. Closing for now. Feel free to reopen in the future.
