### ISSUE TITLE
Providers that are not on map, but still are in filter

### ISSUE THREAD

**Issue by jpechmann** [agrc/starch#69]
Remove the broadband providers that only provide service to business customers (and are therefore ony on locate). Right now the list is:

XO Communications
Cogent Communications
Integra
Interlinx
Level 3 Communications
Skywire Communications
Syringa Networks
Zayo (except this one is new, shouldn't be on there)

Thank you Scott.

**Comment by stdavis** [comment]
Is there a definition query that I can run to remove these?

**Comment by jpechmann** [comment]
Good idea! Use UBBMAP.UBBADMIN.BB_Providers_Table

Definition query **Biz_Only <> 'Y'** will remove all all business providers.
