### ISSUE TITLE
report generation

### ISSUE THREAD

**Issue by steveoh** [agrc/starch#74]
- [ ] As a user I want property and locate reports to be generated nightly for all suresite properties so I can get the reports quickly.
- [ ] As a user I want to get a stylized report of the property with the locate information **after** the suresite information so I can easily find information and that it looks pleasing to my eye.
- [ ] The report contents should be the same as the report in the existing site popup.

**Comment by stdavis** [comment]
This should have been in agrc/ironing-board.
