### ISSUE TITLE
Data Refresh

### ISSUE THREAD

**Issue by jpechmann** [agrc/starch#79]
I updated data in UBB BB_Service yesterday, and the updates are not being reflected on broadband.utah.gov/map. @stdavis, when you get a chance, can you check it out? The validation script ran fine. 

The change was to 3 mobile providers (AT&T, T-Mobile, Verizon) and they should all have last verified dates of 12/31/2015.

Thank you!

**Comment by stdavis** [comment]
@jpechmann Would you mind checking again? I think that the data is updated in production now.

**Comment by jpechmann** [comment]
@stdavis works now, thank you!
